[tool.black]
line-length = 120
target-version = ["py310"]
extend-exclude = "\\.venv|build|dist"

[tool.ruff]
target-version = "py310"
line-length = 120
exclude = [".venv", "build", "dist"]

[tool.ruff.lint]
select = ["E", "F"]
ignore = ["E501", "E712", "E722", "F401", "F821", "F841", "F541"]

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = "-q"


