[tool.black]
line-length = 100
target-version = ["py310"]
exclude = [".venv", "build", "dist"]

[tool.ruff]
target-version = "py310"
line-length = 100
exclude = [".venv", "build", "dist"]

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]
ignore = []

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = "-q"


